---
- name: Shut down previous server
  become:
    yes
  shell: sudo docker-compose down -d
  args:
    chdir: '/home/ubuntu/COMP90024/COMP90024/crawler'

#- name: Clear none images if any
#  become:
#    yes
#  shell: sudo docker rmi $(sudo docker images -f "dangling=true" -q)
#  args:
#    chdir: '/home/ubuntu'

- name: Remove directory
  shell: sudo rm -r ./COMP90024
  args:
    chdir: '/home/ubuntu'

- name: Install git
  become: yes
  ansible.builtin.apt:
    name: ['git']
    state: latest
    install_recommends: no
    update_cache: yes

- name: creates directory
  file:
    path: '/home/ubuntu/COMP90024'
    state: directory

- name: git clone repo
  shell: git clone https://github.com/zisenwang/COMP90024.git
  args:
    chdir: '/home/ubuntu/COMP90024'

- name: git pull lastest repo
  shell: git pull origin
  args:
    chdir: '/home/ubuntu/COMP90024/COMP90024'
    
- name: send config file to server
  copy:
    src: "{{ configb }}"
    dest: '/home/ubuntu/COMP90024/COMP90024/crawler'

- name: Start server
  become:
    yes
  shell: sudo docker-compose up --build -d
  args:
    chdir: '/home/ubuntu/COMP90024/COMP90024/crawler'