---
#- name: Print the gateway for each host when defined
#  ansible.builtin.debug:
#    msg: Hello

- name: Stop couchdb in the docker
  become: yes
  docker_container:
    name: couchdb
    state: absent

- name: Create and start couchdb in the docker
  become: yes
  docker_container:
    name: couchdb
    image: "ibmcom/couchdb3:{{ version }}"
    state: started
    recreate: true
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    volumes:
      - /volume/couchdb/data
    pull: yes
    env:
      COUCHDB_USER: "{{ username }}"
      COUCHDB_PASSWORD: "{{ password }}"
      COUCHDB_SECRET: "{{ cookie }}"
      ERL_FLAGS: "-setcookie \"{{ cookie }}\" -name \"couchdb@{{ inventory_hostname }}\""