# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: COMP90024
instance_flavor: uom.mse.2c9g

# Volume
volumes:
  - vol_name: v1
    vol_size: 50
  - vol_name: v2
    vol_size: 50
  - vol_name: v3
    vol_size: 50
  - vol_name: v4
    vol_size: 50

# Security group
security_groups:
  - name: admin
    description: "rules for server"
  - name: couch_cluster
    description: "rules for couch cluster"

security_group_rules_servers:
  - name: admin
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: admin
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: admin
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: admin
    protocol: tcp
    port_range_min: 8000
    port_range_max: 8000
    remote_ip_prefix: 0.0.0.0/0
  - name: admin
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0

security_group_rules_cluster:
  - name: couch_cluster
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_group: couch_cluster
  - name: couch_cluster
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_group: couch_cluster
  - name: couch_cluster
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_group: couch_cluster

# Instance
instances:
  - name: server1
    volumes: ['v1']
  - name: server2
    volumes: ['v2']
  - name: server3
    volumes: ['v3']
  - name: server4
    volumes: ['v4']


