---
- hosts: DATA_NODES
  vars_files:
    - host_vars/config.yaml
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ../config/COMP90024.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  gather_facts: true
  roles:
    - role: crawler-restart
